export const dummy =  [
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Presiden Joko Widodo mengatakan saat ini muncul fenomena ramai-ramai negara menutup keran ekspor pangan. Selengkapnya ...",
        "hdThumbnail": "https://i.ytimg.com/vi/V_ZBVXjGQRI/hqdefault.jpg",
        "id": "V_ZBVXjGQRI",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-08-31T13:00:23Z",
        "thumbnail": "https://i.ytimg.com/vi/V_ZBVXjGQRI/default.jpg",
        "title": "Muncul Fenomena Ngeri Di Dunia, 19 Negara Setop Ekspor Pangan"
    },
    {
        "channelId": "UCER4rvDnRBPr_ncYW4UCZjg",
        "channelTitle": "tvOneNews ",
        "description": "IBF, https://www.tvOnenews.com - [FULL] Krisis Pangan, Waspada Bahaya Kelaparan | IBF tvOne Musim kering berkepanjangan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/L4iJu9eKqtw/hqdefault.jpg",
        "id": "L4iJu9eKqtw",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-10-04T14:39:12Z",
        "thumbnail": "https://i.ytimg.com/vi/L4iJu9eKqtw/default.jpg",
        "title": "[FULL] Krisis Pangan, Waspada Bahaya Kelaparan | IBF tvOne"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Badan Pangan Nasional meminta masyarakat agar tidak khawatir terhadap pasokan beras. Sebab lewat kerjasama dengan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/2mVCne9xmPc/hqdefault.jpg",
        "id": "2mVCne9xmPc",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-06-08T12:03:13Z",
        "thumbnail": "https://i.ytimg.com/vi/2mVCne9xmPc/default.jpg",
        "title": "Jangan Panik! Ini Antisipasi Harga Pangan Naik"
    },
    {
        "channelId": "UCJmNywTIJojwjCKzfs0lgNw",
        "channelTitle": "Bisniscom",
        "description": "Importir Beras India harus gigit jari setelah India memutuskan menahan ekspor beras non-basmati mereka untuk menjaga ...",
        "hdThumbnail": "https://i.ytimg.com/vi/d1kPXRCqvA0/hqdefault.jpg",
        "id": "d1kPXRCqvA0",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-07-31T12:00:36Z",
        "thumbnail": "https://i.ytimg.com/vi/d1kPXRCqvA0/default.jpg",
        "title": "Dunia Terancam Krisis Pangan Imbas India Setop Ekspor Beras"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Jakarta, CNBC Indonesia- Presiden Joko Widodo menyatakan krisis pangan di depan mata. Hal ini diungkapkan Jokowi dalam ...",
        "hdThumbnail": "https://i.ytimg.com/vi/O7WeHZpmHJ4/hqdefault.jpg",
        "id": "O7WeHZpmHJ4",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-09-15T11:13:41Z",
        "thumbnail": "https://i.ytimg.com/vi/O7WeHZpmHJ4/default.jpg",
        "title": "Jokowi Warning! Ancaman Krisis Pangan di Depan Mata"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Dear Pengganti Jokowi, Ahli Peringatkan Ada Ancaman Intai RI https://bit.ly/3MAFkgJ Ancaman krisis global menjadi salah satu ...",
        "hdThumbnail": "https://i.ytimg.com/vi/9fNbFIbN3Lk/hqdefault.jpg",
        "id": "9fNbFIbN3Lk",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-05-17T07:03:43Z",
        "thumbnail": "https://i.ytimg.com/vi/9fNbFIbN3Lk/default.jpg",
        "title": "Krisis Pangan Mengancam Dunia, Nasib RI di Ujung Tanduk"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Asian Development Bank (ADB) mencatat, jumlah penduduk miskin di Asia bertambah 64,4 juta orang akibat lonjakan harga ...",
        "hdThumbnail": "https://i.ytimg.com/vi/iKEF8DilZMU/hqdefault.jpg",
        "id": "iKEF8DilZMU",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-08-22T06:58:43Z",
        "thumbnail": "https://i.ytimg.com/vi/iKEF8DilZMU/default.jpg",
        "title": "ADB: Lonjakan Harga Pangan, Warga Miskin Asia Tambah 64,4 Juta"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Investor asing mempercayakan dana mereka dikelola Indonesia menjadi modal. Hal ini tercermin dari penerimaan penanaman ...",
        "hdThumbnail": "https://i.ytimg.com/vi/BvsoAEBmjU0/hqdefault.jpg",
        "id": "BvsoAEBmjU0",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-07-21T11:54:25Z",
        "thumbnail": "https://i.ytimg.com/vi/BvsoAEBmjU0/default.jpg",
        "title": "Investor Asing Serbu RI Hingga Krisis Pangan Ancam Dunia"
    },
    {
        "channelId": "UCER4rvDnRBPr_ncYW4UCZjg",
        "channelTitle": "tvOneNews ",
        "description": "Jakarta, https://www.tvOnenews.com - Informasi Terbaru Kenaikan Harga Bahan Pangan di Jakarta | Kabar Pagi tvOne Saksikan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/YaEWvyicFhg/hqdefault.jpg",
        "id": "YaEWvyicFhg",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-06-17T02:30:09Z",
        "thumbnail": "https://i.ytimg.com/vi/YaEWvyicFhg/default.jpg",
        "title": "Informasi Terbaru Kenaikan Harga Bahan Pangan di Jakarta | Kabar Pagi tvOne"
    },
    {
        "channelId": "UC5BMIWZe9isJXLZZWPWvBlg",
        "channelTitle": "KOMPASTV",
        "description": "NUSA DUA BALI, KOMPAS.TV - Menteri Keuangan dan Gubernur Bank Sentral negara-negara G20, hari ini melanjutkan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/BOG5g_1oExw/hqdefault.jpg",
        "id": "BOG5g_1oExw",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-07-16T07:40:49Z",
        "thumbnail": "https://i.ytimg.com/vi/BOG5g_1oExw/default.jpg",
        "title": "G20 Bahas Krisis Pangan &amp; Energi Dunia, Sri Mulyani : Akhir 2022 Harga Pangan Bisa Naik 20 Persen!"
    },
    {
        "channelId": "UCER4rvDnRBPr_ncYW4UCZjg",
        "channelTitle": "tvOneNews ",
        "description": "Breaking News, https://www.tvOnenews.com - Relawan MER-C: Masyarakat Gaza Sedang Alami Krisis Pangan dan Air Bersih ...",
        "hdThumbnail": "https://i.ytimg.com/vi/zeQtJ4rgTr4/hqdefault.jpg",
        "id": "zeQtJ4rgTr4",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-10-16T16:05:14Z",
        "thumbnail": "https://i.ytimg.com/vi/zeQtJ4rgTr4/default.jpg",
        "title": "Relawan MER-C: Masyarakat Gaza Sedang Alami Krisis Pangan dan Air Bersih | Breaking News tvOne"
    },
    {
        "channelId": "UC46q-QSvoJz-1iSxPeuOqWA",
        "channelTitle": "BBC News Indonesia",
        "description": "Demi mencegah ancaman krisis pangan akibat pandemi Covid-19 yang berkepanjangan serta perang Rusia-Ukraina, Presiden ...",
        "hdThumbnail": "https://i.ytimg.com/vi/Zv_6jPUDAM4/hqdefault.jpg",
        "id": "Zv_6jPUDAM4",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-03-15T09:20:12Z",
        "thumbnail": "https://i.ytimg.com/vi/Zv_6jPUDAM4/default.jpg",
        "title": "Program lumbung pangan nasional: Ribuan hektare kebun dan sawah gagal panen - BBC News Indonesia"
    },
    {
        "channelId": "UC5BMIWZe9isJXLZZWPWvBlg",
        "channelTitle": "KOMPASTV",
        "description": "JAKARTA, KOMPAS.TV - Harga beras terus meroket naik. Pemerintah menyebut, sejumlah faktor menjadi penyebab naiknya ...",
        "hdThumbnail": "https://i.ytimg.com/vi/TkP45AhVEZg/hqdefault.jpg",
        "id": "TkP45AhVEZg",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-09-11T13:22:09Z",
        "thumbnail": "https://i.ytimg.com/vi/TkP45AhVEZg/default.jpg",
        "title": "Harga Beras Terus Meroket Naik, Apa Upaya Pemerintah?"
    },
    {
        "channelId": "UCER4rvDnRBPr_ncYW4UCZjg",
        "channelTitle": "tvOneNews ",
        "description": "Jakarta, https://www.tvOnenews.com - Menghadapi tantangan krisis pangan global, Indonesia telah menyusun serangkaian ...",
        "hdThumbnail": "https://i.ytimg.com/vi/_4YvxwcSoqc/hqdefault.jpg",
        "id": "_4YvxwcSoqc",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-06-15T15:40:11Z",
        "thumbnail": "https://i.ytimg.com/vi/_4YvxwcSoqc/default.jpg",
        "title": "Strategi Indonesia Menghadapi Krisis Pangan | Kabar Utama tvOne"
    },
    {
        "channelId": "UCoSkllfpgmFHtbVK835QaQg",
        "channelTitle": "Official iNews",
        "description": "Beberapa hari terakhir, harga telur dan daging ayam potong mengalami kenaikan cukup tinggi. Hal ini kembali dikeluhkan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/2MJUOti9Fsg/hqdefault.jpg",
        "id": "2MJUOti9Fsg",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-05-27T06:28:30Z",
        "thumbnail": "https://i.ytimg.com/vi/2MJUOti9Fsg/default.jpg",
        "title": "Dampak Kenaikan Harga Pangan, Warteg di Cihampelas Kurangi Porsi Lauk"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Kenaikan harga beras terus berlanjut dan pecah rekor. Pada Kamis 21 September 2023 berdasarkan data BI, harga beras ...",
        "hdThumbnail": "https://i.ytimg.com/vi/XzvrBUttNVM/hqdefault.jpg",
        "id": "XzvrBUttNVM",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-09-22T03:09:56Z",
        "thumbnail": "https://i.ytimg.com/vi/XzvrBUttNVM/default.jpg",
        "title": "Harga Beras Hingga Gula Pecah Rekor! Krisis Pangan Mengancam?"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Pemerintah RI tengah mewaspadai dampak ketidakpastian harga-harga komoditas global terhadap pasokan dan keamanan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/Eq8Mlb51pDo/hqdefault.jpg",
        "id": "Eq8Mlb51pDo",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-08-02T06:14:38Z",
        "thumbnail": "https://i.ytimg.com/vi/Eq8Mlb51pDo/default.jpg",
        "title": "Krisis Pangan Ancam Dunia, Bapanas Yakin Stok Pangan RI Aman!"
    },
    {
        "channelId": "UCKII0Ml9S5wneKbHswmUrIQ",
        "channelTitle": "CNN Indonesia",
        "description": "Pemimpin Korea Utara Kim Jong Un membuat terobosan dengan memulai proyek rumah kaca besar dan pembangunan 10 ribu ...",
        "hdThumbnail": "https://i.ytimg.com/vi/ePG5yA-AFU4/hqdefault.jpg",
        "id": "ePG5yA-AFU4",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-02-17T10:00:23Z",
        "thumbnail": "https://i.ytimg.com/vi/ePG5yA-AFU4/default.jpg",
        "title": "Diduga Krisis Pangan, Korea Utara Bangun Rumah Kaca"
    },
    {
        "channelId": "UCER4rvDnRBPr_ncYW4UCZjg",
        "channelTitle": "tvOneNews ",
        "description": "Kabar Pagi, https://www.tvOnenews.com - Badan Pangan Nasional Peringati Hari Keamanan Pangan Sedunia | Kabar Pagi ...",
        "hdThumbnail": "https://i.ytimg.com/vi/6F9E3dj9oPc/hqdefault.jpg",
        "id": "6F9E3dj9oPc",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-06-10T02:04:15Z",
        "thumbnail": "https://i.ytimg.com/vi/6F9E3dj9oPc/default.jpg",
        "title": "Badan Pangan Nasional Peringati Hari Keamanan Pangan Sedunia | Kabar Pagi tvOne"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Jelang hari raya Idul Adha harga sejumlah komoditas di DKI Jakarta merangkak naik. Salah satunya cabai rawit merah yang ...",
        "hdThumbnail": "https://i.ytimg.com/vi/xn3ySQ7ipjM/hqdefault.jpg",
        "id": "xn3ySQ7ipjM",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-06-07T07:20:30Z",
        "thumbnail": "https://i.ytimg.com/vi/xn3ySQ7ipjM/default.jpg",
        "title": "Harga Pangan Menjelang Iduladha"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Presiden Joko Widodo mendorong riset dan inovasi sektor Pertanian sebagai strategi Indonesia mengatasi berbagai tantangan ...",
        "hdThumbnail": "https://i.ytimg.com/vi/GBSSJ_iUSCY/hqdefault.jpg",
        "id": "GBSSJ_iUSCY",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-09-21T04:30:04Z",
        "thumbnail": "https://i.ytimg.com/vi/GBSSJ_iUSCY/default.jpg",
        "title": "Jokowi Waspadai Krisis Pangan, Riset &amp; Inovasi Pertanian Siap Akomodir?"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Selain beras harga berbagai kebutuhan pokok lainnya kompak menanjak pada awal pekan ini. Kenaikan bahkan ada yang ...",
        "hdThumbnail": "https://i.ytimg.com/vi/6c2FphTcB-E/hqdefault.jpg",
        "id": "6c2FphTcB-E",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-10-09T13:20:39Z",
        "thumbnail": "https://i.ytimg.com/vi/6c2FphTcB-E/default.jpg",
        "title": "Bukan Cuma Beras, Harga Pangan Lain Juga Beterbangan"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Badan Pangan Nasional (Bapanas) bersama Kementerian/Lembaga dan stakeholder terus berupaya memastikan stabilitas ...",
        "hdThumbnail": "https://i.ytimg.com/vi/1Nb8qtRB2-U/hqdefault.jpg",
        "id": "1Nb8qtRB2-U",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-07-14T03:04:38Z",
        "thumbnail": "https://i.ytimg.com/vi/1Nb8qtRB2-U/default.jpg",
        "title": "Bapanas &amp; Nasib Ketahanan Pangan di Tengah Ancaman Kekeringan"
    },
    {
        "channelId": "UCKII0Ml9S5wneKbHswmUrIQ",
        "channelTitle": "CNN Indonesia",
        "description": "Strategi Indonesia Hadapi Masalah Ketahanan Pangan - Right Angle Kementan.",
        "hdThumbnail": "https://i.ytimg.com/vi/ahhmdqyMNT8/hqdefault.jpg",
        "id": "ahhmdqyMNT8",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-06-20T07:59:09Z",
        "thumbnail": "https://i.ytimg.com/vi/ahhmdqyMNT8/default.jpg",
        "title": "Strategi Indonesia Hadapi Masalah Ketahanan Pangan - Right Angle Kementan"
    },
    {
        "channelId": "UCGN9JsnkvK05v2lnTI_-uGA",
        "channelTitle": "CNBC Indonesia",
        "description": "Harga pangan di beberapa wilayah di Indonesia masih mengalami kenaikan. Arief Prasetyo Adi Kepala Badan Pangan Nasional ...",
        "hdThumbnail": "https://i.ytimg.com/vi/-tf0Fth3918/hqdefault.jpg",
        "id": "-tf0Fth3918",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-06-08T12:19:36Z",
        "thumbnail": "https://i.ytimg.com/vi/-tf0Fth3918/default.jpg",
        "title": "Bunda, Ini Lho Penyebab Harga Pangan Naik"
    },
    {
        "channelId": "UC5BMIWZe9isJXLZZWPWvBlg",
        "channelTitle": "KOMPASTV",
        "description": "JAKARTA, KOMPAS.TV - Pemerintah mulai melaksanakan Sensus Pertanian 2023 untuk mengetahui kondisi komprehensif ...",
        "hdThumbnail": "https://i.ytimg.com/vi/tTKDUwLEaLQ/hqdefault.jpg",
        "id": "tTKDUwLEaLQ",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-06-06T12:31:20Z",
        "thumbnail": "https://i.ytimg.com/vi/tTKDUwLEaLQ/default.jpg",
        "title": "Perkuat Ketahanan Pangan Indonesia di Tengah Ancaman Krisis Global, BPS Gelar Sensus Pertanian!"
    },
    {
        "channelId": "UC5BMIWZe9isJXLZZWPWvBlg",
        "channelTitle": "KOMPASTV",
        "description": "JAKARTA, KOMPAS.TV - Presiden Joko Widodo meninjau harga sejumlah komoditas pangan di Pasar Jatinegara Jakarta Timur ...",
        "hdThumbnail": "https://i.ytimg.com/vi/LHNPte7wTXg/hqdefault.jpg",
        "id": "LHNPte7wTXg",
        "liveBroadcastContent": "none",
        "publishedAt": "2023-09-19T05:46:12Z",
        "thumbnail": "https://i.ytimg.com/vi/LHNPte7wTXg/default.jpg",
        "title": "Harapan Jokowi Usai Tinjau Harga Bahan Pangan di Pasar Jatinegara: Harga Beras Turun 2-3 Minggu"
    },
    {
        "channelId": "UCn8U8GiaHZNP9pFKzl3Cwlg",
        "channelTitle": "IDX Channel Insights",
        "description": "Stasiun televisi ini pertama kali siaran pada tanggal 29 September 2010 hingga saat ini. IDX Channel memiliki tagline Your ...",
        "hdThumbnail": "https://i.ytimg.com/vi/PAcIeuk6ldo/hqdefault.jpg",
        "id": "PAcIeuk6ldo",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-12-07T10:14:31Z",
        "thumbnail": "https://i.ytimg.com/vi/PAcIeuk6ldo/default.jpg",
        "title": "BUMN Siap Turut Jaga Ketahanan Pangan Nasional | NEWS SCREEN 07/12/2022"
    },
    {
        "channelId": "UCKII0Ml9S5wneKbHswmUrIQ",
        "channelTitle": "CNN Indonesia",
        "description": "Krisis pangan global diprediksi akan semakin memburuk di tahun 2022. Sehingga dibutuhkan kerjasama dan usaha keras, dalam ...",
        "hdThumbnail": "https://i.ytimg.com/vi/nekAuAq44rQ/hqdefault.jpg",
        "id": "nekAuAq44rQ",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-07-19T01:45:01Z",
        "thumbnail": "https://i.ytimg.com/vi/nekAuAq44rQ/default.jpg",
        "title": "Ancaman Krisis Pangan Global Makin Mencekam"
    },
    {
        "channelId": "UCKII0Ml9S5wneKbHswmUrIQ",
        "channelTitle": "CNN Indonesia",
        "description": "Ketahanan pangan nasional menjadi upaya pemerintah untuk menangkal ancaman krisis pangan global yang tengah ...",
        "hdThumbnail": "https://i.ytimg.com/vi/Bour7vGk0-Q/hqdefault.jpg",
        "id": "Bour7vGk0-Q",
        "liveBroadcastContent": "none",
        "publishedAt": "2022-10-11T08:45:00Z",
        "thumbnail": "https://i.ytimg.com/vi/Bour7vGk0-Q/default.jpg",
        "title": "Hindari Krisis Dengan Menciptakan Ketahanan Pangan Nasional"
    }
]